# This file was generated by GoReleaser. DO NOT EDIT.
cask "ax-rc" do
  version "0.1.2-rc.3"

  on_macos do
    on_intel do
      sha256 "7851012e29426a54fa82156732251e075fe91f13d0b716db3dd2fe53cbcb284d"
      url "https://github.com/agentswitch-org/ax/releases/download/v#{version}/ax_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "fda585306aad39f5f9a436542fd8b693d2604816cf91c9ce683a15e064fbd8f2"
      url "https://github.com/agentswitch-org/ax/releases/download/v#{version}/ax_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "6176fb39dcc934f80a17531da0664773391e2e7f4ab951244a3f2a6565e3485d"
      url "https://github.com/agentswitch-org/ax/releases/download/v#{version}/ax_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "d3e2d394b6cfdf98468f1fd26ef88fd848554ee227f65789b280d88c9fb7bb6a"
      url "https://github.com/agentswitch-org/ax/releases/download/v#{version}/ax_#{version}_linux_arm64.tar.gz"
    end
  end

  name "ax-rc"
  desc "Session switcher for LLM CLI agents"
  homepage "https://github.com/agentswitch-org/ax"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ax"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/ax"]
    end
  end

  # No zap stanza required

end
