# This file was generated by GoReleaser. DO NOT EDIT.
cask "ax-rc" do
  version "0.1.2-rc.1"

  on_macos do
    on_intel do
      sha256 "d4c0bfeee96bbcb190f748d2daf9a23a6f12a2215ca439e27d074e9bc4083075"
      url "https://github.com/agentswitch-org/ax/releases/download/v#{version}/ax_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "485d4484639c8eb87bd4dce542a3bd1597080b9688d3091afa724a232b60a03e"
      url "https://github.com/agentswitch-org/ax/releases/download/v#{version}/ax_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "09501b4a220a6051dbd2f58245c29fecfefa40fd2ab336a9c7926ebe64d455e2"
      url "https://github.com/agentswitch-org/ax/releases/download/v#{version}/ax_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "28da602bdc272c1180e6179698c4807bb9d11814913e09450b848d9883b3c975"
      url "https://github.com/agentswitch-org/ax/releases/download/v#{version}/ax_#{version}_linux_arm64.tar.gz"
    end
  end

  name "ax-rc"
  desc "Session switcher for LLM CLI agents"
  homepage "https://github.com/agentswitch-org/ax"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ax"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/ax"]
    end
  end

  # No zap stanza required

end
