# This file was generated by GoReleaser. DO NOT EDIT.
cask "ax-rc" do
  version "0.1.1-rc.1"

  on_macos do
    on_intel do
      sha256 "5044bc9b987e4d27859c377944bb1497cc03eb5f60fdec8c41c5a1aad2661b28"
      url "https://github.com/agentswitch-org/ax/releases/download/v#{version}/ax_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "7ed16933756cf0830c8be4a0a80ed36490add5f6a3ec6360f1eda3bedeaf8b59"
      url "https://github.com/agentswitch-org/ax/releases/download/v#{version}/ax_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "df532c2df32f97d6a11cc2b8fd9ecbf8e6402048153d20c2443db664d1b34164"
      url "https://github.com/agentswitch-org/ax/releases/download/v#{version}/ax_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "e1cdb4f5e81ea58e0da2fa106af6dae3c10808e99696fc5a345aea736cc5b0d8"
      url "https://github.com/agentswitch-org/ax/releases/download/v#{version}/ax_#{version}_linux_arm64.tar.gz"
    end
  end

  name "ax-rc"
  desc "Session switcher for LLM CLI agents"
  homepage "https://github.com/agentswitch-org/ax"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ax"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/ax"]
    end
  end

  # No zap stanza required

end
