# This file was generated by GoReleaser. DO NOT EDIT.
cask "ax" do
  version "0.1.0"

  on_macos do
    on_intel do
      sha256 "2aec9755d7edaa036879ae5b09eefd95bcc363fc0e823f214360dcd02b07fb84"
      url "https://github.com/agentswitch-org/ax/releases/download/v#{version}/ax_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "3572b899d2a88415c9e1b378468676cbc7c07d418b0034466a5c1db9470e7e76"
      url "https://github.com/agentswitch-org/ax/releases/download/v#{version}/ax_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "58cef2ef4dacd04b98fe09803d5a0a1862a277a897610aaa6d2874e745d4c14b"
      url "https://github.com/agentswitch-org/ax/releases/download/v#{version}/ax_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "22d16b3188b218aea2ebe5d307c8307117c9f9510bf32cbeb566f9397bd3fb8d"
      url "https://github.com/agentswitch-org/ax/releases/download/v#{version}/ax_#{version}_linux_arm64.tar.gz"
    end
  end

  name "ax"
  desc "Session switcher for LLM CLI agents"
  homepage "https://github.com/agentswitch-org/ax"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ax"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/ax"]
    end
  end

  # No zap stanza required

end
