# This file was generated by GoReleaser. DO NOT EDIT.
cask "ax" do
  version "0.1.2"

  on_macos do
    on_intel do
      sha256 "0f8e56d414d4827a7d7b3982e9b53da7820951f03e44e7bb918d406aef8083da"
      url "https://github.com/agentswitch-org/ax/releases/download/v#{version}/ax_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "5cbb5d2cefc4ff572141c4d643215b919ebad57f0ae4c8d6c587623d00f366d0"
      url "https://github.com/agentswitch-org/ax/releases/download/v#{version}/ax_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "62bb6fec79e519e04e70f1e0dbf8c4927e5458b260b4c19d47b1e1ffb4821b02"
      url "https://github.com/agentswitch-org/ax/releases/download/v#{version}/ax_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "a7f6ffa53953f99bd456bbf35ca2f5a2fe7baf796452e74b6687b370e4d3c7a7"
      url "https://github.com/agentswitch-org/ax/releases/download/v#{version}/ax_#{version}_linux_arm64.tar.gz"
    end
  end

  name "ax"
  desc "Session switcher for LLM CLI agents"
  homepage "https://github.com/agentswitch-org/ax"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ax"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/ax"]
    end
  end

  # No zap stanza required

end
