# This file was generated by GoReleaser. DO NOT EDIT.
cask "ax" do
  version "0.1.1"

  on_macos do
    on_intel do
      sha256 "1ecc309b5487dc2ed030eefa7a44b0993b8af3986d9880158b498d59107cfdf7"
      url "https://github.com/agentswitch-org/ax/releases/download/v#{version}/ax_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "5c9e5b1dbb62a2e276d332963804befd49eb085b6ddbe31581b9701fb0d555b7"
      url "https://github.com/agentswitch-org/ax/releases/download/v#{version}/ax_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "19568da663c1d23d0a79674d27a193ee11c58227e6e59c6a191b4f87629ce721"
      url "https://github.com/agentswitch-org/ax/releases/download/v#{version}/ax_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "3773482fac3ff4649e894c5ce926ab1e604257decc7fc9ff2720c7a08258b021"
      url "https://github.com/agentswitch-org/ax/releases/download/v#{version}/ax_#{version}_linux_arm64.tar.gz"
    end
  end

  name "ax"
  desc "Session switcher for LLM CLI agents"
  homepage "https://github.com/agentswitch-org/ax"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ax"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/ax"]
    end
  end

  # No zap stanza required

end
